auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: D:/Automated Incident Response System/loki
  storage:
    filesystem:
      chunks_directory: D:/Automated Incident Response System/loki/chunks
      rules_directory: D:/Automated Incident Response System/loki/rules

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: D:/Automated Incident Response System/loki/boltdb-shipper-active
    cache_location: D:/Automated Incident Response System/loki/boltdb-shipper-cache
    cache_ttl: 24h
  filesystem:
    directory: D:/Automated Incident Response System/loki/chunks

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  chunk_retain_period: 30s
  wal:
    enabled: true
    dir: D:/Automated Incident Response System/loki/wal

limits_config:
  retention_period: 744h
  allow_structured_metadata: false

table_manager:
  retention_deletes_enabled: true
  retention_period: 744h

compactor:
  working_directory: D:/Automated Incident Response System/loki/compactor
