---
- name: Network Optimization
  hosts: "{{ target_host }}"
  become: yes
  tasks:
    - name: Check network status
      shell: "netstat -tuln"
      register: network_status

    - name: Log network connections
      debug:
        msg: "Network connections:\n{{ network_status.stdout }}"

    - name: Check network interface status
      shell: "ip addr show"
      register: interface_status

    - name: Log interface status
      debug:
        msg: "Interface status:\n{{ interface_status.stdout }}"

    - name: Restart networking service
      systemd:
        name: networking
        state: restarted
      ignore_errors: yes

    - name: Clear network routing cache
      shell: "ip route flush cache"
      ignore_errors: yes

    - name: Optimize network parameters
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        state: present
      with_items:
        - { key: 'net.ipv4.tcp_fin_timeout', value: '30' }
        - { key: 'net.ipv4.tcp_keepalive_time', value: '1200' }
        - { key: 'net.ipv4.tcp_max_syn_backlog', value: '2048' }
        - { key: 'net.ipv4.tcp_tw_reuse', value: '1' }
      ignore_errors: yes 